### ISSUE TITLE
Error adding HS107

### ISSUE THREAD

**Issue by Magno99900** [DaveGut/Depreciated---SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#20]
When I try to add the HS107 I'm getting an error and won't add through either app.  Let me know what info you need so I can help you diagnose this.

**Comment by DaveGut** [comment]
I just now bought a HS107.  Will find out the command structure next week and get back to you when updated.

Dave

**Comment by DaveGut** [comment]
The new version (3.5) located at DaveGut/TP-Link-SmartThings supports the HS107 plug.  One nuance.  If a hub installation, you will have to change the label after install to your device label.  For Kasa, it works OK.

You should update both the Smart App and Device Handlers (copy and replace file contents).  Then add the HS107.  I recommend the lite Service manager.  Same functionality, less bells and whistles and probably more reliable (due to reduced number of internet links.

Dave
